# Generated by Django 3.2.13 on 2022-09-28 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('start_money', models.IntegerField()),
                ('closure_money', models.IntegerField()),
                ('closure_paper', models.IntegerField()),
                ('money', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('wasfa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('real_money', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
