# Generated by Django 3.2.13 on 2022-12-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closure',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
