# Generated by Django 3.2.12 on 2022-04-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20220427_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayementstat',
            old_name='prove_of_payement',
            new_name='proof_of_payement',
        ),
    ]
