# Generated by Django 3.2.12 on 2022-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmed',
            name='dosage',
            field=models.CharField(max_length=50, null=True, verbose_name='dosage'),
        ),
    ]
