# Generated by Django 3.2.12 on 2022-04-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmed', '0002_alter_addmed_dosage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addmed',
        ),
    ]
