# Generated by Django 3.2.12 on 2022-04-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addmed', '0003_delete_addmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('dci', models.CharField(max_length=250, verbose_name='dci')),
                ('dosage', models.CharField(max_length=50, verbose_name='dosage')),
                ('cond', models.CharField(max_length=25, verbose_name='cond')),
                ('types', models.CharField(max_length=50, verbose_name='types')),
            ],
        ),
    ]
