# Generated by Django 3.2.12 on 2022-04-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmed', '0004_addmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmed',
            name='types',
            field=models.CharField(choices=[('MEDICAMENT', 'MEDICAMENT'), ('ARTICLE', 'ARTICLE')], max_length=50, verbose_name='types'),
        ),
    ]
