# Generated by Django 3.2.12 on 2022-04-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmed', '0005_alter_addmed_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmed',
            name='types',
        ),
    ]
