# Generated by Django 3.2.12 on 2022-04-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmed', '0006_remove_addmed_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='full_name')),
            ],
        ),
    ]
