# Generated by Django 3.2.12 on 2022-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmed', '0008_alter_addmed_cond'),
    ]

    operations = [
        migrations.AddField(
            model_name='addart',
            name='tag',
            field=models.CharField(default='article', max_length=10, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='addmed',
            name='tag',
            field=models.CharField(default='medicament', max_length=10, verbose_name='tag'),
        ),
    ]
