# Generated by Django 3.2.12 on 2022-05-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmed', '0009_auto_20220522_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addart',
            name='tag',
            field=models.CharField(default='A', max_length=10, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='addmed',
            name='tag',
            field=models.CharField(default='M', max_length=10, verbose_name='tag'),
        ),
    ]
