# Generated by Django 3.2.12 on 2022-05-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmed', '0010_auto_20220523_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addart',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='addmed',
            name='tag',
        ),
    ]
