# Generated by Django 3.2.12 on 2022-05-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmed', '0011_auto_20220523_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='addart',
            name='tag',
            field=models.CharField(default='A', max_length=1, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='addmed',
            name='tag',
            field=models.CharField(default='M', max_length=1, verbose_name='tag'),
        ),
    ]
