# Generated by Django 3.2.13 on 2022-10-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20221001_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='paitent_age',
            new_name='patient_age',
        ),
    ]
