# Generated by Django 3.2.13 on 2022-10-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_patients_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='labo',
            name='hba1c',
            field=models.BooleanField(default=False),
        ),
    ]
