# Generated by Django 3.2.13 on 2022-10-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_labo_hba1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='labo',
            name='delevered',
            field=models.BooleanField(default=False),
        ),
    ]
