# Generated by Django 3.2.13 on 2022-11-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_labo_delevered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labo',
            name='hba1c',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
