# Generated by Django 3.2.12 on 2022-04-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mycmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250, verbose_name='product')),
                ('prod_stat', models.CharField(max_length=100, verbose_name='prod_stat')),
                ('cmded', models.BooleanField(default=False, verbose_name='cmded')),
                ('received', models.BooleanField(default=False, verbose_name='received')),
            ],
        ),
    ]
