# Generated by Django 3.2.12 on 2022-04-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycmd',
            name='indisponible',
            field=models.BooleanField(default=False, verbose_name='received'),
        ),
    ]
