# Generated by Django 3.2.12 on 2022-04-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0005_alter_mycmd_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycmd',
            name='qtt',
            field=models.IntegerField(max_length=4, null=True, verbose_name='qtt'),
        ),
    ]
