# Generated by Django 3.2.12 on 2022-04-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0006_mycmd_qtt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycmd',
            name='qtt',
            field=models.IntegerField(null=True, verbose_name='qtt'),
        ),
    ]
