# Generated by Django 3.2.12 on 2022-04-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0007_alter_mycmd_qtt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycmd',
            name='qtt',
            field=models.IntegerField(blank=True, null=True, verbose_name='qtt'),
        ),
    ]
