# Generated by Django 3.2.12 on 2022-04-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0012_userpayementstat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPayementStat',
        ),
    ]
