# Generated by Django 3.2.12 on 2022-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0013_delete_userpayementstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycmd',
            name='received_0',
            field=models.IntegerField(default=0, verbose_name='received_0'),
        ),
        migrations.AlterField(
            model_name='mycmd',
            name='indisponible',
            field=models.BooleanField(default=False, verbose_name='indisponible'),
        ),
    ]
