# Generated by Django 3.2.12 on 2022-05-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0014_auto_20220513_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250, verbose_name='product')),
                ('cmded', models.IntegerField(max_length=10, verbose_name='cmded')),
                ('received', models.IntegerField(max_length=10, verbose_name='cmded')),
                ('indisponible', models.IntegerField(max_length=10, verbose_name='cmded')),
                ('deleted', models.IntegerField(max_length=10, verbose_name='cmded')),
            ],
        ),
        migrations.AddField(
            model_name='mycmd',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
