# Generated by Django 3.2.12 on 2022-05-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0015_auto_20220514_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stattable',
            name='cmded',
            field=models.IntegerField(verbose_name='cmded'),
        ),
        migrations.AlterField(
            model_name='stattable',
            name='deleted',
            field=models.IntegerField(verbose_name='cmded'),
        ),
        migrations.AlterField(
            model_name='stattable',
            name='indisponible',
            field=models.IntegerField(verbose_name='cmded'),
        ),
        migrations.AlterField(
            model_name='stattable',
            name='received',
            field=models.IntegerField(verbose_name='cmded'),
        ),
    ]
