# Generated by Django 3.2.12 on 2022-05-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0016_auto_20220514_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stattable',
            name='cmded',
            field=models.IntegerField(null=True, verbose_name='cmded'),
        ),
    ]
