# Generated by Django 3.2.12 on 2022-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0017_alter_stattable_cmded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stattable',
            name='deleted',
            field=models.IntegerField(null=True, verbose_name='cmded'),
        ),
        migrations.AlterField(
            model_name='stattable',
            name='indisponible',
            field=models.IntegerField(null=True, verbose_name='cmded'),
        ),
        migrations.AlterField(
            model_name='stattable',
            name='received',
            field=models.IntegerField(null=True, verbose_name='cmded'),
        ),
    ]
