# Generated by Django 3.2.12 on 2022-05-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0018_auto_20220514_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stattable',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='stattable',
            name='indisponible',
            field=models.IntegerField(null=True, verbose_name='indisponible'),
        ),
        migrations.AlterField(
            model_name='stattable',
            name='received',
            field=models.IntegerField(null=True, verbose_name='received'),
        ),
    ]
