# Generated by Django 3.2.12 on 2022-05-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0021_alter_mycmd_qtt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycmd',
            name='qtt',
            field=models.IntegerField(default=0, verbose_name='qtt'),
        ),
    ]
