# Generated by Django 3.2.12 on 2022-05-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0022_alter_mycmd_qtt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycmd',
            name='tag',
            field=models.CharField(default='medicament', max_length=10, verbose_name='tag'),
        ),
    ]
