# Generated by Django 3.2.12 on 2022-05-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makecmd', '0023_mycmd_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycmd',
            name='tag',
        ),
    ]
